### ISSUE TITLE
IaC and Cloud Provider - docs

### ISSUE THREAD

**Issue by dpgraham4401** [USEPA/haztrak#480]
# 🚀 Feature Request

Haztrak does not have a method (checked into VCS) to deploy to anything outside the docker-compose for local development. It would be really cool to see haztrak deployed to a cloud cloud service provider. However, just going through something like the AWS console is not reproducible by someone who cloned this repo (or forked it), however we could implement this using Infrastructure as code  (IaC). 

## Reasons to implment
The research involved before implementing IaC for haztrak, as well as attempting it, could be beneficial to the project direction, as it would likely illustrate areas that we need to focus on or improve. For example, I know many of our queryset usage is likely inefficient and may perform several db hits. however, given that the only deployment environment haztrak ever sees is the local workstation, we can't get a good sense and what a real user experience would look/feel like. 

## ToDO

- [x] Research Cloud providers
    - [x] AWS
    - [x] GCP
    - [x] Azure
    - [x] k8 (not a service)
    - [x] oracle 
- [x] Research IaC tools
    - [x] Terraform Research
    - [x] CloudFormation Research
    - [x] Pulumi
    - [x] Alternative IaC tools

**Comment by dpgraham4401** [comment]
# IaC tools
of the available tools, terraform appears to have the widest adoption in industry and the biggest ecosystem of providers community support. According to the Pulumi docs (paraphrasing) the reason to use pulumi is to avoid having to learn HCL (hashicorp config language I believe) since you can use pulumi using several popular programming languages, and the flexibility that using a full fledged language affords you. However, the prevailing thought amoungst those that work with this kind of tooling is that using a full language is probably more of a foot gun than a plus. 

Outside of those two options, the remainder of the popular IaC tools appear to not be cloud agnostic. This may not be a problem if we ok with tying the haztrak deployment to a certain cloud provider, howerver terraform does sound more appealing for this reason.

**Comment by dpgraham4401** [comment]
# Cloud providers
Some initial thoughts, AWS is by far the most widely used cloud service provider. By default, using the most widely adopted tool/service/etc. with this project aligns with the projects goals (to be reusable as an overkill POC). The most widely adopted option is also enticing to me, personally, since it gives me a chance to get some hands on experience with AWS. Choosing the most widely adopted service provider also means that I can lean on experience of others in the community who have come across the same problems I encounter

**Comment by dpgraham4401** [comment]
# Kubernetes (Container Orchestration)
If we would like to deploy haztrak in using a container orchestrator, such as [k8](https://kubernetes.io/), then what are the options in the major 3.

## GCP
Google allows us to deploy 1 free zonal cluster per month for free. beyond that, it's $0.10 per hour.
https://cloud.google.com/kubernetes-engine/pricing#cluster_management_fee_and_free_tier

## Azure
Azure also has a free tier usage for option but I can't get details because i'm getting a Azure error (lol 😆) on their website. 

<img width="392" alt="image" src="https://github.com/USEPA/haztrak/assets/43794491/031c95c6-3443-4cb5-a6a1-71016d6723e5">


## AWS
AWS does not actually have a free tier version of EKS (google has a pricing structure that allows 1 free zonal per month, azure has a free version details forthecoming). For what it's worth, the pricing (EKS on outpost) is the same as GCP.

**Comment by dpgraham4401** [comment]
# serverless
If we decide to go for a serverless infrastructure, it seems like all three of the major players have always free tier levels for 
GCP  - Cloud Run
AWS - lambda
Azure - Azure request

One of the big downsides is, if we go this route, then we build for the cloud provider that we choose. As i understand it, transferring serverless functions between cloud providers is not really an option.
